apiary.apib

* referral endpointy
* odstraneni syntakticky erroru
* odstraneni z object property sikme uvozovky

referrals: documented endpoints and objects

---

apiary.apib

Na to prisla Zuzka, ze nam to nesedi s kodem a `EMPLOYMENT` je vice konzistentni s ostatnimi hodnotami

revolving loan: employee -> employment, addresses compatible with current endpoints

---

apiary.apib

AccountUpgradeApplicationRequest updated with bankStatements array field

Proof of income documents for AccountUpgrade

---

apiary.apib

Revolving Loan Contract Type enum updated
Added bankStatementMonth field to AccountUpgradeApplicationResponse
PersonalDocument object definition removed as out-dated

Revolving Loan type update and add bBank statement month

---

apiary.apib

Upravil jsem chyby co jsem našel během práce.

Fix acoount upgrade

---

apiary.apib

Move placeOfBirth, dateOfBirth and gender under IdentityDocument object
Rename deliverToHomeAddress so that the field corresponds more with form logic

Change deliverToHomeAddress field name

---

apiary.apib

loan: add valid enum fields for scopeOfBusiness

---

apiary.apib

monthlyGrossIncome field renamed in account upgrade endpoint

Rename monthlyGrossIncome to quarterlyGrossIncome for account upgrade endpoint

---

apiary.apib

Added optional cjEvent attribute to POST /account/registration request body

---

apiary.apib

podpora pro presmerovani z BBC na FE

added bankBusinessCardReturnUrl

---

apiary.apib

Add missing otpCode to AccountUpgrade request

Add missing otpCode to AccountUpgrade request

---

apiary.apib

DELETE endpoint has insufficient type description and parameter naming
differs from POST

fix(pushNotification): improve description

---

apiary.apib

* Merge file upload property to `SimpleFile` and remove `File` object.
* Remove redundant `HistoryFile` object, replace with `SimpleFile`.
cc @MPdevelopers @jsilhan @zzuzzy

refactor: use single File object

---

apiary.apib

- card description object
- list of cards
- card detail
- card blocking
- card activation
- card show pin
- changing card limits

KNJ-8133 payment card manipulation

---

apiary.apib

- Add Revolving loan billing and transaction endpoints
- Remove outdated Transactions endpoint 
- Remove outdated MoneyTransaction object

Add Revolving loan billing and transaction endpoints

---

apiary.apib

Add accountType to My Profile endpoint
Remove outdated Card object
Correct typo in DeferredPaymentInfo
Correct description of filtering over transaction by date

Add accountType to My Profile endpoint

---

apiary.apib

add referenceNumber filter to transaction endpoint

KNJ-8066 / SS-2274 Create request for transaction complaint

---

apiary.apib

* feat(cams): added ability to defer the billing

KNJ-8343 Ability to defer the billing

---

apiary.apib

- add example with code for case when customer is younger then 18

KNJ-8645 patch account upgrade request - add example

---

apiary.apib

* feat(payment): added ability to pay billing

KNJ-8342 Ability to pay billing

---

apiary.apib

* feat(billing): added endpoint to retrieve billings applications

KNJ-8548 Billing - endpoint to retrieve billing's applications

---

apiary.apib

feat(DomesticPaymentOrder) added field qrCode

KNJ-7773 New field DomesticPaymentOrder.qrCode

---

apiary.apib

Finální verze pro zapracování připomínek k PR na BE.

KNJ-7203 Telco consent update

---

apiary.apib

Add missing CSOB bic code to banks list

KNJ-9308 Add CSOB bic code to banks list
